### ISSUE TITLE
Radar speed & egomotion raw data

### ISSUE THREAD

**Issue by shawrby** [aimotive/aimotive_dataset#1]
Hi,

Thank you for your awesome work!

1) Is the speed of radar raw data a relative speed with meter/second(m/s) unit?
How should the ego-motion compensated speed be extracted?

2) What's the meaning the each parameter and value in egomotion/egomotion2.json?

Thanks in advance.

**Comment by TamasMatuszka** [comment]
Hi,

I collected the answers to your questions.

1. The raw radar data is the radial speed with a meter/second unit, you can find the detailed sensor description here: 
https://www.smartmicro.com/fileadmin/media/Downloads/Automotive_Radar/Sensor_Data_Sheets_76-81GHz/UMRR-11_Type_132_Automotive_Data_Sheet.pdf

You need the ego-motion only if you want to transform it into an absolute coordinate system.

2. egomotion.json parameters:
key: camera frame id, value: RT matrix from body coordinate system to ECEF
egmotion2.json parameters:
key: camera frame id (like in egomotion.json)
value is a dictionary where:
- RT_ECEF_body is the same transformation matrix as in egomotion.json
- enh_sep is the latitude, longitude, height separation, i.e. GNSS error
- rph_sep is the roll, pitch, heading separation, i.e. IMU error
- time: GNSS+INS device timestamp
- time_host: synchronized host timestamp (from camera metadata)

**Comment by TamasMatuszka** [comment]
@shawrby 
You are right, not every sequence has an egomotion2.json file. However, egomotion.json also contains the RT_ECEF_body information that can be used for compensation (we also used it also during our experiments for collecting more than one LiDAR sweep).
