### ISSUE TITLE
Upload on Kaggle

### ISSUE THREAD

**Issue by aadimator** [aimotive/aimotive_dataset#2]
Can you kindly make this dataset public on Kaggle as well? That way those who don't have much compute can easily utilize the Kaggle platform to play/train on this dataset. It'll be a huge help.

If you want, I can upload this to Kaggle. Let me know what you think about that.

Thanks

**Comment by TamasMatuszka** [comment]
@aadimator 
This is a great idea! We are making a minor update on the dataset next week. Please wait; I will let you know when the update is finished. After that, I will upload it to Kaggle too.

**Comment by TamasMatuszka** [comment]
@aadimator I uploaded the dataset to Kaggle, you can find it here:
https://www.kaggle.com/datasets/tamasmatuszka/aimotive-multimodal-dataset

**Comment by aadimator** [comment]
Many thanks. Is the update finished? The one you were talking about.

**Comment by TamasMatuszka** [comment]
Yes, this is the latest, updated dataset.
