### ISSUE TITLE
where lidar in your dataset 

### ISSUE THREAD

**Issue by liluxing153** [aimotive/aimotive_dataset#3]
Hi  ，
After I downloaded the whole dataset, it was about 80g. Under the sensor folder, the lidar data is not found. Where is the lidar data?

thk

**Comment by TamasMatuszka** [comment]
Hi @liluxing153,

You can find the LiDAR point clouds in the dynamic/raw-revolutions folder. A short description of the dataset structure is described in [Kaggle](https://www.kaggle.com/datasets/tamasmatuszka/aimotive-multimodal-dataset).

I'm currently working on the detailed dataset documentation which will include a detailed description of our dataset using [datasheets for dataset](https://arxiv.org/abs/1803.09010). I'll update the repository's readme when it's done.

**Comment by TamasMatuszka** [comment]
Hi @liluxing153,

I updated the repository and the preprint, you can find the dataset documentation [here](https://arxiv.org/abs/2211.09445).
